 name: UniquePtr with CMake CI and Valgrind

on: 
  push:
  pull_request:
    branches:
      - unique_ptr_homework

jobs:
  ctest:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Create folder - build
      run: mkdir build
    - name: Compile
      working-directory: build
      run: |
        cmake ..
        make
    - name: Run tests
      working-directory: build
      run: ./uniquePtr-ut
      
  valgrind:
    runs-on: ubuntu-latest
    
    steps:
    - name: Run valgrind
    working-directory: build
    run: |
      sudo apt-get update && sudo apt-get install valgrind
      valgrind --leak-check=full ./uniquePtr-ut
   
