name: UniquePtr with CMake CI and Valgrind

on: 
  push:
  pull_request:
    branches:
      - master

jobs:
  ctest:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Create folder - build
      working-directory: homework/unique_ptr/
      run: mkdir build
    - name: Compile
      working-directory: homework/unique_ptr/build
      run: |
        cmake ..
        make
    - name: Run tests
      working-directory: homework/unique_ptr/build
      run: ./uniquePtr-ut
      
  valgrind:
    runs-on: ubuntu-latest
    
    steps:
    - name: Run valgrind
      uses: actions/checkout@master
    - name: Valgrind Instalation
      run: sudo apt install valgrind
    - name: Create folder - build
      working-directory: homework/unique_ptr/
      run: mkdir build
    - name: Compile
      working-directory: homework/unique_ptr/build
      run: |
        cmake ..
        make
    - name: Run Valgrind
      working-directory: homework/unique_ptr/build
      run: valgrind --leak-check=full ./uniquePtr-ut
